# syntax version.
version: "3.7"

volumes:
  php-alpine-cache-v3.9:
  php-alpine-cache-v3.10:
  php-alpine-cache-v3.11:

# services list.
services:
  # base image
  alpine-base:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-base"
    build:
      context: "${PHP_VERSION}/alpine/base"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - "php-alpine-cache-v${ALPINE_VERSION}:/var/cache/apk"

  # swoole image
  alpine-cli:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-cli-v${SWOOLE_VERSION}"
    build:
      context: "${PHP_VERSION}/alpine/cli"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SWOOLE_VERSION: ${SWOOLE_VERSION}
    volumes:
      - "php-alpine-cache-v${ALPINE_VERSION}:/var/cache/apk"

  # dev image
  alpine-dev:
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-dev"
    build:
      context: "${PHP_VERSION}/alpine/dev"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - "php-alpine-cache-v${ALPINE_VERSION}:/var/cache/apk"

  # ubuntu base image
  ubuntu-base:
    image: "hyperf/hyperf:${PHP_VERSION}-ubuntu-v${UBUNTU_VERSION}-base"
    build:
      context: "${PHP_VERSION}/ubuntu/base"
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}

  # swoole image
  ubuntu-cli:
    image: "hyperf/hyperf:${PHP_VERSION}-ubuntu-v${UBUNTU_VERSION}-cli-v${SWOOLE_VERSION}"
    build:
      context: "${PHP_VERSION}/ubuntu/cli"
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        SWOOLE_VERSION: ${SWOOLE_VERSION}
