# syntax version.
version: "3.7"

volumes:
  php-alpine-cache-v3.9:
  php-alpine-cache-v3.10:

# services list.
services:
  # sandbox base image
  alpine-base:
    # target image.
    image: "hyperf/hyperf:${PHP_VERSION}-alpine-v${ALPINE_VERSION}-base"
    build:
      context: "${PHP_VERSION}/alpine/base"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    volumes:
      - "php-alpine-cache-v${ALPINE_VERSION}:/var/cache/apk"