name: Build Base Image

on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Whether publish to dockerhub'
        required: true
        default: false

env:
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

jobs:
  build:
    name: Build Base Image
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: ./build.sh build
      - name: Push Images to Docker Hub
        if: ${{ github.event.inputs.event}}
        run: |
          docker login --username limingxinleo -p $DOCKERHUB_TOKEN
          echo 123


