name: Build Base Image

on:
  push:
  workflow_dispatch:
    inputs:
      event:
        description: 'Input your event'
        required: true
        default: ''

jobs:
  build:
    name: Build Base Image
    runs-on: 'ubuntu-latest'
    env:
      PHP_VERSION: '${{ matrix.php-version }}'
      ALPINE_VERSION: '${{ matrix.alpine-version }}'
    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
        alpine-version: [ '3.16', '3.17', '3.18', '3.19', '3.20', '3.21', '3.22', 'edge' ]
        exclude:
          - php-version: '8.4'
            alpine-version: '3.16'
          - php-version: '8.4'
            alpine-version: '3.17'
          - php-version: '8.4'
            alpine-version: '3.18'
          - php-version: '8.4'
            alpine-version: '3.19'
          - php-version: '8.4'
            alpine-version: '3.20'
          - php-version: '8.3'
            alpine-version: '3.16'
          - php-version: '8.3'
            alpine-version: '3.17'
          - php-version: '8.3'
            alpine-version: '3.18'
          - php-version: '8.2'
            alpine-version: '3.16'
          - php-version: '8.2'
            alpine-version: '3.17'
          - php-version: '8.1'
            alpine-version: '3.20'
          - php-version: '8.1'
            alpine-version: '3.21'
          - php-version: '8.1'
            alpine-version: '3.22'
          - php-version: '8.1'
            alpine-version: 'edge'
      max-parallel: 12
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: limingxinleo
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.php-version }}/alpine/base
          load: true
          tags: hyperf/hyperf:${{ matrix.php-version }}-alpine-v${{ matrix.alpine-version }}-base
          build-args: |
            "ALPINE_VERSION=${{ matrix.alpine-version }}"
      - name: Check
        run: |
          docker run --entrypoint php -v $PWD/tests/base:/opt/www hyperf/hyperf:${{ matrix.php-version }}-alpine-v${{ matrix.alpine-version }}-base /opt/www/openssl.php
      - name: Push
        if: ${{ github.event.inputs.event == 'publish' }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.php-version }}/alpine/base
          push: true
          platforms: linux/amd64,linux/arm64
          tags: hyperf/hyperf:${{ matrix.php-version }}-alpine-v${{ matrix.alpine-version }}-base
          build-args: |
            "ALPINE_VERSION=${{ matrix.alpine-version }}"


