name: Build PHP73 Swoole

on: [push]
env:
  ENGINE: "swoole"
  PHP_VERSION: "7.3"
  SW_VERSION: "v4.5.5"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Build Alpine ${{ matrix.alpine-version }} on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    env:
      ALPINE_VERSION: "${{ matrix.alpine-version }}"
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        alpine-version: ['3.9', '3.10', '3.11']
      max-parallel: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: ./.github/workflows/build.sh
